AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - test/**/*
    - lib/shipengine_rb/utils/base58.rb
    - .pryrc
    - !ruby/regexp /(foo|bar|baz)\.rb/

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 150
  AllowedPatterns: ["^ *# ", "https?://"]

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
