# frozen_string_literal: true

require_relative 'domain/account'
require_relative 'domain/addresses'
require_relative 'domain/batches'
require_relative 'domain/carrier_accounts'
require_relative 'domain/carriers'
require_relative 'domain/documents'
require_relative 'domain/downloads'
require_relative 'domain/insurance'
require_relative 'domain/labels'
require_relative 'domain/ltl'
require_relative 'domain/manifests'
require_relative 'domain/package_pickups'
require_relative 'domain/package_types'
require_relative 'domain/rates'
require_relative 'domain/service_points'
require_relative 'domain/shipments'
require_relative 'domain/tags'
require_relative 'domain/tokens'
require_relative 'domain/tracking'
require_relative 'domain/warehouses'
require_relative 'domain/webhooks'
